unit leerconfig;

interface

uses
  Classes, SysUtils, IniFiles, Forms, Windows;

const
  csIniCONFIGURACIONSection = 'CONFIGURACION';
  csIniCENTINELASection = 'CENTINELA';
  csIniSOSSection = 'SOS';
  csIniCRONOSSection = 'CRONOS';
  csIniPlayerWEBSection = 'PlayerWEB';

  {Section: CONFIGURACION}
  csIniCONFIGURACIONUDPLISTENER = 'UDPLISTENER';
  csIniCONFIGURACIONID = 'ID';
  csIniCONFIGURACIONCREALOGTTY = 'CREALOGTTY';
  csIniCONFIGURACIONCONEXIONNORMAL = 'CONEXIONNORMAL';
  csIniCONFIGURACIONANCHOVENTANACONEXION = 'ANCHOVENTANACONEXION';
  csIniCONFIGURACIONPERIODO = 'PERIODO';
  csIniCONFIGURACIONCBUSCARORDENES = 'CBUSCARORDENES';
  csIniCONFIGURACIONSEPARARCANALES = 'SEPARARCANALES';
  csIniCONFIGURACIONMAXTIEMPODESCARGA = 'MAXTIEMPODESCARGA';
  csIniCONFIGURACIONMINCONEXION = 'MINCONEXION';
  csIniCONFIGURACIONMIN_CONEXION = 'MIN_CONEXION';
  csIniCONFIGURACIONPROPORCION = 'PROPORCION';
  csIniCONFIGURACIONULTIMOCANAL = 'ULTIMOCANAL';
  csIniCONFIGURACIONTCACHE = 'TCACHE';
  csIniCONFIGURACIONNIVELLOG = 'NIVELLOG';
  csIniCONFIGURACIONVAL_INTERVALOALIVE = 'VAL_INTERVALOALIVE';
  csIniCONFIGURACIONUSR_FTP = 'USR_FTP';
  csIniCONFIGURACIONPWD_FTP = 'PWD_FTP';
  csIniCONFIGURACIONCLASECONEX = 'CLASECONEX';
  csIniCONFIGURACIONFTPPASIVO = 'FTPPASIVO';
  csIniCONFIGURACIONMODOFTP = 'MODOFTP';
  csIniCONFIGURACIONURLUDP = 'URLUDP';
  csIniCONFIGURACIONTURLUDP = 'TURLUDP';
  csIniCONFIGURACIONFTP = 'FTP';
  csIniCONFIGURACIONPROXY = 'PROXY';
  csIniCONFIGURACIONPROXYPORT = 'PROXYPORT';
  csIniCONFIGURACIONBWLimit = 'BWLimit';
  csIniCONFIGURACIONCLASENOTIF = 'CLASENOTIF';
  csIniCONFIGURACIONINTERVALOALIVE = 'INTERVALOALIVE';
  csIniCONFIGURACIONVIDEO = 'VIDEO';
  csIniCONFIGURACIONPANTALLAS = 'PANTALLAS';
  csIniCONFIGURACIONMODELOPANTALLA1 = 'MODELOPANTALLA1';
  csIniCONFIGURACIONPANTALLA1 = 'PANTALLA1';
  csIniCONFIGURACIONPANTALLA2 = 'PANTALLA2';
  csIniCONFIGURACIONPANTALLA3 = 'PANTALLA3';
  csIniCONFIGURACIONPANTALLA4 = 'PANTALLA4';
  csIniCONFIGURACIONPANTALLA5 = 'PANTALLA5';
  csIniCONFIGURACIONRATONX = 'RATONX';
  csIniCONFIGURACIONRATONY = 'RATONY';
  csIniCONFIGURACIONRATONW = 'RATONW';
  csIniCONFIGURACIONRATONH = 'RATONH';
  csIniCONFIGURACIONFON_BCO_FLASH = 'FON_BCO_FLASH';
  csIniCONFIGURACIONFON_BCO_VIDEO = 'FON_BCO_VIDEO';
  csIniCONFIGURACIONFON_BCO_IMAGEN = 'FON_BCO_IMAGEN';
  csIniCONFIGURACIONCONSOLATOP = 'CONSOLATOP';
  csIniCONFIGURACIONCONSOLALEFT = 'CONSOLALEFT';
  csIniCONFIGURACIONONOFF = 'ONOFF';
  csIniCONFIGURACIONENCENDIDO = 'ENCENDIDO';
  csIniCONFIGURACIONAPAGADO = 'APAGADO';
  csIniCONFIGURACIONCOD_CLIENTE = 'COD_CLIENTE';
  csIniCONFIGURACIONNOM_UBICACION = 'NOM_UBICACION';
  csIniCONFIGURACIONUSERID = 'USERID';
  csIniCONFIGURACIONCOD_GRUPO = 'COD_GRUPO';
  csIniCONFIGURACIONNOM_ZONA = 'NOM_ZONA';
  csIniCONFIGURACIONZONAHORARIA = 'ZONAHORARIA';
  csIniCONFIGURACIONCPO_LOCAL = 'CPO_LOCAL';
  csIniCONFIGURACIONLANG = 'LANG';
  csIniCONFIGURACIONCOD_SERVICIO = 'COD_SERVICIO';
  csIniCONFIGURACIONFTP1 = 'FTP1';
  csIniCONFIGURACIONPORT1 = 'PORT1';
  csIniCONFIGURACIONPATH1 = 'PATH1';
  csIniCONFIGURACIONPATHCUNIAS1 = 'PATHCUNIAS1';
  csIniCONFIGURACIONPATHORD1 = 'PATHORD1';
  csIniCONFIGURACIONPATHPLAYLIST1 = 'PATHPLAYLIST1';
  csIniCONFIGURACIONPATHPLAYLISTCUNIA1 = 'PATHPLAYLISTCUNIA1';
  csIniCONFIGURACIONPATHPLAYLISTCUNIAS1 = 'PATHPLAYLISTCUNIAS1';
  csIniCONFIGURACIONPATHINI1 = 'PATHINI1';
  csIniCONFIGURACIONPATHJPG1 = 'PATHJPG1';
  csIniCONFIGURACIONPATHMM1 = 'PATHMM1';
  csIniCONFIGURACIONPATHSW1 = 'PATHSW1';
  csIniCONFIGURACIONPATHXMLFondos1 = 'PATHXMLFondos1';
  csIniCONFIGURACIONPATHJPGFondos1 = 'PATHJPGFondos1';
  csIniCONFIGURACIONSYNCMULTIPLAYER = 'SYNCMULTIPLAYER';
  csIniCONFIGURACIONSYNCMULTIPLAYERMASTER = 'SYNCMULTIPLAYERMASTER';
  csIniCONFIGURACIONVIDEORENDERER = 'VIDEORENDERER';
  csIniCONFIGURACIONWEBRENDERER = 'WEBRENDERER';
  csIniCONFIGURACIONMOD_REPRO_MKD = 'MOD_REPRO_MKD';
  csIniCONFIGURACIONURLCACHEDYNA = 'URLCACHEDYNA';
  csIniCONFIGURACIONID_MASTER_CACHE = 'ID_MASTER_CACHE';
  csIniCONFIGURACIONBDAUDIENCIA = 'BDAUDIENCIA';
  csIniCONFIGURACIONLOCAL5555 = 'LOCAL5555';
  csIniCONFIGURACIONVERSION = 'VERSION';
  csIniCONFIGURACIONIDSISTEMA = 'IDSISTEMA';
  csIniCONFIGURACIONBACKOFFICE = 'BACKOFFICE';
  csIniCONFIGURACIONFFPLAYERFIT = 'FFPLAYERFIT';
  csIniCONFIGURACIONCOM_PORT = 'COM_PORT';
  csIniCONFIGURACIONFFLOGGER = 'FFLOGGER';
  csIniCONFIGURACIONDEBUGTTY = 'DEBUGTTY';
  csIniCONFIGURACIONCHRNOPOPMENU = 'CHRNOPOPMENU';
  csIniCONFIGURACIONUDP_MCAST_LISTENER = 'UDP_MCAST_LISTENER';
  csIniCONFIGURACIONMCASTPORT = 'MCASTPORT';
  csIniCONFIGURACIONCONTROLNTP = 'CONTROLNTP';
  csIniCONFIGURACIONWEBEXTERNACHR = 'WEBEXTERNACHR';
  csIniCONFIGURACIONFICPASTILLAVIDEO = 'FICPASTILLAVIDEO';
  csIniCONFIGURACIONPASTILLAVIDEO = 'PASTILLAVIDEO';
  csIniCONFIGURACIONREFRESHWEB = 'REFRESHWEB';
  csIniCONFIGURACIONAPIWEB = 'APIWEB';
  csIniCONFIGURACIONAPIUSER = 'APIUSER';
  csIniCONFIGURACIONAPIPASS = 'APIPASS';
  csIniCONFIGURACIONAPIPORT = 'APIPORT';
  csIniCONFIGURACIONSEG_BLOQUEO_ALIVE = 'SEG_BLOQUEO_ALIVE';
  csIniCONFIGURACIONSYNCMCASTGROUP = 'SYNCMCASTGROUP';
  csIniCONFIGURACIONSYNCMCASTPORT = 'SYNCMCASTPORT';
  csIniCONFIGURACIONCICLOCUNRELLENO = 'CICLOCUNRELLENO';
  csIniCONFIGURACIONURLUDPORD = 'URLUDPORD';
  csIniCONFIGURACIONAUDIENCIAINTERACTIVA = 'AUDIENCIAINTERACTIVA';
  csIniCONFIGURACIONPULLORDENES = 'PULLORDENES';

  {Section: CENTINELA}
  csIniCENTINELAHBEAT = 'HBEAT';
  csIniCENTINELADIALOGOS = 'DIALOGOS';
  csIniCENTINELATIMEOUT_BLOQUEO = 'TIMEOUT_BLOQUEO';
  csIniCENTINELATIMEOUT_CPUALTA = 'TIMEOUT_CPUALTA';
  csIniCENTINELACONFW = 'CONFW';
  csIniCENTINELAMAXIMO_CPU = 'MAXIMO_CPU';
  csIniCENTINELAMAXIMO_MEMORIA = 'MAXIMO_MEMORIA';
  csIniCENTINELACLASENOTIF_CENTINELA = 'CLASENOTIF_CENTINELA';
  csIniCENTINELACLASE_COMANDOS = 'CLASE_COMANDOS';
  csIniCENTINELAVERSION = 'VERSION';
  csIniCENTINELAPROGRAMAS_NO_CERRAR = 'PROGRAMAS_NO_CERRAR';
  csIniCENTINELAHBEATUDP_TIME = 'HBEATUDP_TIME';

  {Section: SOS}
  csIniSOSINI_EMERGENCIA = 'INI_EMERGENCIA';

  {Section: CRONOS}
  csIniCRONOSTMRCRONOS = 'TMRCRONOS';
  csIniCRONOSCENTEMITE = 'CENTEMITE';
  csIniCRONOSREPESCACUNIA = 'REPESCACUNIA';
  csIniCRONOSBOFFSET = 'BOFFSET';

  {Section: PlayerWEB}
  csIniPlayerWEBurl_startup = 'url_startup';
  csIniPlayerWEBurl_base_ws = 'url_base_ws';
  csIniPlayerWEBancho = 'ancho';
  csIniPlayerWEBalto = 'alto';
  csIniPlayerWEBx = 'x';
  csIniPlayerWEBy = 'y';
  csIniPlayerWEBintervalo_refresh = 'intervalo_refresh';
  csIniPlayerWEBintervalo_check = 'intervalo_check';
  csIniPlayerWEBfuncion_check = 'funcion_check';
  csIniPlayerWEBintervalo_info = 'intervalo_info';

type
  TIniOptions = class(TObject)
  private
    {Section: CONFIGURACION}
    FCONFIGURACIONUDPLISTENER: string;
    FCONFIGURACIONID: Integer;
    FCONFIGURACIONCREALOGTTY: string;
    FCONFIGURACIONCONEXIONNORMAL: TDateTime;
    FCONFIGURACIONANCHOVENTANACONEXION: Integer;
    FCONFIGURACIONPERIODO: Integer;
    FCONFIGURACIONCBUSCARORDENES: Integer;
    FCONFIGURACIONSEPARARCANALES: string;
    FCONFIGURACIONMAXTIEMPODESCARGA: TDateTime;
    FCONFIGURACIONMINCONEXION: Integer;
    FCONFIGURACIONMIN_CONEXION: Integer;
    FCONFIGURACIONPROPORCION: Integer;
    FCONFIGURACIONULTIMOCANAL: Integer;
    FCONFIGURACIONTCACHE: Integer;
    FCONFIGURACIONNIVELLOG: Integer;
    FCONFIGURACIONVAL_INTERVALOALIVE: Integer;
    FCONFIGURACIONUSR_FTP: string;
    FCONFIGURACIONPWD_FTP: string;
    FCONFIGURACIONCLASECONEX: Integer;
    FCONFIGURACIONFTPPASIVO: string;
    FCONFIGURACIONMODOFTP: string;
    FCONFIGURACIONURLUDP: string;
    FCONFIGURACIONTURLUDP: Integer;
    FCONFIGURACIONFTP: string;
    FCONFIGURACIONPROXY: string;
    FCONFIGURACIONPROXYPORT: string;
    FCONFIGURACIONBWLimit: Integer;
    FCONFIGURACIONCLASENOTIF: string;
    FCONFIGURACIONINTERVALOALIVE: Integer;
    FCONFIGURACIONVIDEO: string;
    FCONFIGURACIONPANTALLAS: Integer;
    FCONFIGURACIONMODELOPANTALLA1: string;
    FCONFIGURACIONPANTALLA1: string;
    FCONFIGURACIONPANTALLA2: string;
    FCONFIGURACIONPANTALLA3: string;
    FCONFIGURACIONPANTALLA4: string;
    FCONFIGURACIONPANTALLA5: string;
    FCONFIGURACIONRATONX: Integer;
    FCONFIGURACIONRATONY: Integer;
    FCONFIGURACIONRATONW: Integer;
    FCONFIGURACIONRATONH: Integer;
    FCONFIGURACIONFON_BCO_FLASH: string;
    FCONFIGURACIONFON_BCO_VIDEO: string;
    FCONFIGURACIONFON_BCO_IMAGEN: string;
    FCONFIGURACIONCONSOLATOP: Integer;
    FCONFIGURACIONCONSOLALEFT: Integer;
    FCONFIGURACIONONOFF: string;
    FCONFIGURACIONENCENDIDO: TDateTime;
    FCONFIGURACIONAPAGADO: TDateTime;
    FCONFIGURACIONCOD_CLIENTE: Integer;
    FCONFIGURACIONNOM_UBICACION: string;
    FCONFIGURACIONUSERID: string;
    FCONFIGURACIONCOD_GRUPO: Integer;
    FCONFIGURACIONNOM_ZONA: string;
    FCONFIGURACIONZONAHORARIA: Integer;
    FCONFIGURACIONCPO_LOCAL: Integer;
    FCONFIGURACIONLANG: string;
    FCONFIGURACIONCOD_SERVICIO: Real;
    FCONFIGURACIONFTP1: string;
    FCONFIGURACIONPORT1: Integer;
    FCONFIGURACIONPATH1: string;
    FCONFIGURACIONPATHCUNIAS1: string;
    FCONFIGURACIONPATHORD1: string;
    FCONFIGURACIONPATHPLAYLIST1: string;
    FCONFIGURACIONPATHPLAYLISTCUNIA1: string;
    FCONFIGURACIONPATHPLAYLISTCUNIAS1: string;
    FCONFIGURACIONPATHINI1: string;
    FCONFIGURACIONPATHJPG1: string;
    FCONFIGURACIONPATHMM1: string;
    FCONFIGURACIONPATHSW1: string;
    FCONFIGURACIONPATHXMLFondos1: string;
    FCONFIGURACIONPATHJPGFondos1: string;
    FCONFIGURACIONSYNCMULTIPLAYER: Integer;
    FCONFIGURACIONSYNCMULTIPLAYERMASTER: Integer;
    FCONFIGURACIONVIDEORENDERER: Integer;
    FCONFIGURACIONWEBRENDERER: Integer;
    FCONFIGURACIONMOD_REPRO_MKD: Integer;
    FCONFIGURACIONURLCACHEDYNA: string;
    FCONFIGURACIONID_MASTER_CACHE: Integer;
    FCONFIGURACIONBDAUDIENCIA: string;
    FCONFIGURACIONLOCAL5555: string;
    FCONFIGURACIONVERSION: string;
    FCONFIGURACIONIDSISTEMA: Integer;
    FCONFIGURACIONBACKOFFICE: Integer;
    FCONFIGURACIONFFPLAYERFIT: string;
    FCONFIGURACIONCOM_PORT: Integer;
    FCONFIGURACIONFFLOGGER: Integer;
    FCONFIGURACIONDEBUGTTY: Integer;
    FCONFIGURACIONCHRNOPOPMENU: string;
    FCONFIGURACIONUDP_MCAST_LISTENER: string;
    FCONFIGURACIONMCASTPORT: Integer;
    FCONFIGURACIONCONTROLNTP: string;
    FCONFIGURACIONWEBEXTERNACHR: string;
    FCONFIGURACIONFICPASTILLAVIDEO: string;
    FCONFIGURACIONPASTILLAVIDEO: string;
    FCONFIGURACIONREFRESHWEB: string;
    FCONFIGURACIONAPIWEB: string;
    FCONFIGURACIONAPIUSER: string;
    FCONFIGURACIONAPIPASS: string;
    FCONFIGURACIONAPIPORT: Integer;
    FCONFIGURACIONSEG_BLOQUEO_ALIVE: Integer;
    FCONFIGURACIONSYNCMCASTGROUP: string;
    FCONFIGURACIONSYNCMCASTPORT: Integer;
    FCONFIGURACIONCICLOCUNRELLENO: Integer;
    FCONFIGURACIONURLUDPORD: string;
    FCONFIGURACIONAUDIENCIAINTERACTIVA: string;
    FCONFIGURACIONPULLORDENES: string;

    {Section: CENTINELA}
    FCENTINELAHBEAT: string;
    FCENTINELADIALOGOS: string;
    FCENTINELATIMEOUT_BLOQUEO: Integer;
    FCENTINELATIMEOUT_CPUALTA: Integer;
    FCENTINELACONFW: string;
    FCENTINELAMAXIMO_CPU: Integer;
    FCENTINELAMAXIMO_MEMORIA: Integer;
    FCENTINELACLASENOTIF_CENTINELA: string;
    FCENTINELACLASE_COMANDOS: string;
    FCENTINELAVERSION: string;
    FCENTINELAPROGRAMAS_NO_CERRAR: string;
    FCENTINELAHBEATUDP_TIME: Integer;

    {Section: SOS}
    FSOSINI_EMERGENCIA: string;

    {Section: CRONOS}
    FCRONOSTMRCRONOS: Integer;
    FCRONOSCENTEMITE: Integer;
    FCRONOSREPESCACUNIA: Integer;
    FCRONOSBOFFSET: Integer;

    {Section: PlayerWEB}
    FPlayerWEBurl_startup: string;
    FPlayerWEBurl_base_ws: string;
    FPlayerWEBancho: Integer;
    FPlayerWEBalto: Integer;
    FPlayerWEBx: Integer;
    FPlayerWEBy: Integer;
    FPlayerWEBintervalo_refresh: Integer;
    FPlayerWEBintervalo_check: Integer;
    FPlayerWEBfuncion_check: string;
    FPlayerWEBintervalo_info: Integer;
  public
    procedure LoadSettings(Ini: TIniFile);
    procedure SaveSettings(Ini: TIniFile);
    
    procedure LoadFromFile(const FileName: string);
    procedure SaveToFile(const FileName: string);

    {Section: CONFIGURACION}
    property CONFIGURACIONUDPLISTENER: string read FCONFIGURACIONUDPLISTENER write FCONFIGURACIONUDPLISTENER;
    property CONFIGURACIONID: Integer read FCONFIGURACIONID write FCONFIGURACIONID;
    property CONFIGURACIONCREALOGTTY: string read FCONFIGURACIONCREALOGTTY write FCONFIGURACIONCREALOGTTY;
    property CONFIGURACIONCONEXIONNORMAL: TDateTime read FCONFIGURACIONCONEXIONNORMAL write FCONFIGURACIONCONEXIONNORMAL;
    property CONFIGURACIONANCHOVENTANACONEXION: Integer read FCONFIGURACIONANCHOVENTANACONEXION write FCONFIGURACIONANCHOVENTANACONEXION;
    property CONFIGURACIONPERIODO: Integer read FCONFIGURACIONPERIODO write FCONFIGURACIONPERIODO;
    property CONFIGURACIONCBUSCARORDENES: Integer read FCONFIGURACIONCBUSCARORDENES write FCONFIGURACIONCBUSCARORDENES;
    property CONFIGURACIONSEPARARCANALES: string read FCONFIGURACIONSEPARARCANALES write FCONFIGURACIONSEPARARCANALES;
    property CONFIGURACIONMAXTIEMPODESCARGA: TDateTime read FCONFIGURACIONMAXTIEMPODESCARGA write FCONFIGURACIONMAXTIEMPODESCARGA;
    property CONFIGURACIONMINCONEXION: Integer read FCONFIGURACIONMINCONEXION write FCONFIGURACIONMINCONEXION;
    property CONFIGURACIONMIN_CONEXION: Integer read FCONFIGURACIONMIN_CONEXION write FCONFIGURACIONMIN_CONEXION;
    property CONFIGURACIONPROPORCION: Integer read FCONFIGURACIONPROPORCION write FCONFIGURACIONPROPORCION;
    property CONFIGURACIONULTIMOCANAL: Integer read FCONFIGURACIONULTIMOCANAL write FCONFIGURACIONULTIMOCANAL;
    property CONFIGURACIONTCACHE: Integer read FCONFIGURACIONTCACHE write FCONFIGURACIONTCACHE;
    property CONFIGURACIONNIVELLOG: Integer read FCONFIGURACIONNIVELLOG write FCONFIGURACIONNIVELLOG;
    property CONFIGURACIONVAL_INTERVALOALIVE: Integer read FCONFIGURACIONVAL_INTERVALOALIVE write FCONFIGURACIONVAL_INTERVALOALIVE;
    property CONFIGURACIONUSR_FTP: string read FCONFIGURACIONUSR_FTP write FCONFIGURACIONUSR_FTP;
    property CONFIGURACIONPWD_FTP: string read FCONFIGURACIONPWD_FTP write FCONFIGURACIONPWD_FTP;
    property CONFIGURACIONCLASECONEX: Integer read FCONFIGURACIONCLASECONEX write FCONFIGURACIONCLASECONEX;
    property CONFIGURACIONFTPPASIVO: string read FCONFIGURACIONFTPPASIVO write FCONFIGURACIONFTPPASIVO;
    property CONFIGURACIONMODOFTP: string read FCONFIGURACIONMODOFTP write FCONFIGURACIONMODOFTP;
    property CONFIGURACIONURLUDP: string read FCONFIGURACIONURLUDP write FCONFIGURACIONURLUDP;
    property CONFIGURACIONTURLUDP: Integer read FCONFIGURACIONTURLUDP write FCONFIGURACIONTURLUDP;
    property CONFIGURACIONFTP: string read FCONFIGURACIONFTP write FCONFIGURACIONFTP;
    property CONFIGURACIONPROXY: string read FCONFIGURACIONPROXY write FCONFIGURACIONPROXY;
    property CONFIGURACIONPROXYPORT: string read FCONFIGURACIONPROXYPORT write FCONFIGURACIONPROXYPORT;
    property CONFIGURACIONBWLimit: Integer read FCONFIGURACIONBWLimit write FCONFIGURACIONBWLimit;
    property CONFIGURACIONCLASENOTIF: string read FCONFIGURACIONCLASENOTIF write FCONFIGURACIONCLASENOTIF;
    property CONFIGURACIONINTERVALOALIVE: Integer read FCONFIGURACIONINTERVALOALIVE write FCONFIGURACIONINTERVALOALIVE;
    property CONFIGURACIONVIDEO: string read FCONFIGURACIONVIDEO write FCONFIGURACIONVIDEO;
    property CONFIGURACIONPANTALLAS: Integer read FCONFIGURACIONPANTALLAS write FCONFIGURACIONPANTALLAS;
    property CONFIGURACIONMODELOPANTALLA1: string read FCONFIGURACIONMODELOPANTALLA1 write FCONFIGURACIONMODELOPANTALLA1;
    property CONFIGURACIONPANTALLA1: string read FCONFIGURACIONPANTALLA1 write FCONFIGURACIONPANTALLA1;
    property CONFIGURACIONPANTALLA2: string read FCONFIGURACIONPANTALLA2 write FCONFIGURACIONPANTALLA2;
    property CONFIGURACIONPANTALLA3: string read FCONFIGURACIONPANTALLA3 write FCONFIGURACIONPANTALLA3;
    property CONFIGURACIONPANTALLA4: string read FCONFIGURACIONPANTALLA4 write FCONFIGURACIONPANTALLA4;
    property CONFIGURACIONPANTALLA5: string read FCONFIGURACIONPANTALLA5 write FCONFIGURACIONPANTALLA5;
    property CONFIGURACIONRATONX: Integer read FCONFIGURACIONRATONX write FCONFIGURACIONRATONX;
    property CONFIGURACIONRATONY: Integer read FCONFIGURACIONRATONY write FCONFIGURACIONRATONY;
    property CONFIGURACIONRATONW: Integer read FCONFIGURACIONRATONW write FCONFIGURACIONRATONW;
    property CONFIGURACIONRATONH: Integer read FCONFIGURACIONRATONH write FCONFIGURACIONRATONH;
    property CONFIGURACIONFON_BCO_FLASH: string read FCONFIGURACIONFON_BCO_FLASH write FCONFIGURACIONFON_BCO_FLASH;
    property CONFIGURACIONFON_BCO_VIDEO: string read FCONFIGURACIONFON_BCO_VIDEO write FCONFIGURACIONFON_BCO_VIDEO;
    property CONFIGURACIONFON_BCO_IMAGEN: string read FCONFIGURACIONFON_BCO_IMAGEN write FCONFIGURACIONFON_BCO_IMAGEN;
    property CONFIGURACIONCONSOLATOP: Integer read FCONFIGURACIONCONSOLATOP write FCONFIGURACIONCONSOLATOP;
    property CONFIGURACIONCONSOLALEFT: Integer read FCONFIGURACIONCONSOLALEFT write FCONFIGURACIONCONSOLALEFT;
    property CONFIGURACIONONOFF: string read FCONFIGURACIONONOFF write FCONFIGURACIONONOFF;
    property CONFIGURACIONENCENDIDO: TDateTime read FCONFIGURACIONENCENDIDO write FCONFIGURACIONENCENDIDO;
    property CONFIGURACIONAPAGADO: TDateTime read FCONFIGURACIONAPAGADO write FCONFIGURACIONAPAGADO;
    property CONFIGURACIONCOD_CLIENTE: Integer read FCONFIGURACIONCOD_CLIENTE write FCONFIGURACIONCOD_CLIENTE;
    property CONFIGURACIONNOM_UBICACION: string read FCONFIGURACIONNOM_UBICACION write FCONFIGURACIONNOM_UBICACION;
    property CONFIGURACIONUSERID: string read FCONFIGURACIONUSERID write FCONFIGURACIONUSERID;
    property CONFIGURACIONCOD_GRUPO: Integer read FCONFIGURACIONCOD_GRUPO write FCONFIGURACIONCOD_GRUPO;
    property CONFIGURACIONNOM_ZONA: string read FCONFIGURACIONNOM_ZONA write FCONFIGURACIONNOM_ZONA;
    property CONFIGURACIONZONAHORARIA: Integer read FCONFIGURACIONZONAHORARIA write FCONFIGURACIONZONAHORARIA;
    property CONFIGURACIONCPO_LOCAL: Integer read FCONFIGURACIONCPO_LOCAL write FCONFIGURACIONCPO_LOCAL;
    property CONFIGURACIONLANG: string read FCONFIGURACIONLANG write FCONFIGURACIONLANG;
    property CONFIGURACIONCOD_SERVICIO: Real read FCONFIGURACIONCOD_SERVICIO write FCONFIGURACIONCOD_SERVICIO;
    property CONFIGURACIONFTP1: string read FCONFIGURACIONFTP1 write FCONFIGURACIONFTP1;
    property CONFIGURACIONPORT1: Integer read FCONFIGURACIONPORT1 write FCONFIGURACIONPORT1;
    property CONFIGURACIONPATH1: string read FCONFIGURACIONPATH1 write FCONFIGURACIONPATH1;
    property CONFIGURACIONPATHCUNIAS1: string read FCONFIGURACIONPATHCUNIAS1 write FCONFIGURACIONPATHCUNIAS1;
    property CONFIGURACIONPATHORD1: string read FCONFIGURACIONPATHORD1 write FCONFIGURACIONPATHORD1;
    property CONFIGURACIONPATHPLAYLIST1: string read FCONFIGURACIONPATHPLAYLIST1 write FCONFIGURACIONPATHPLAYLIST1;
    property CONFIGURACIONPATHPLAYLISTCUNIA1: string read FCONFIGURACIONPATHPLAYLISTCUNIA1 write FCONFIGURACIONPATHPLAYLISTCUNIA1;
    property CONFIGURACIONPATHPLAYLISTCUNIAS1: string read FCONFIGURACIONPATHPLAYLISTCUNIAS1 write FCONFIGURACIONPATHPLAYLISTCUNIAS1;
    property CONFIGURACIONPATHINI1: string read FCONFIGURACIONPATHINI1 write FCONFIGURACIONPATHINI1;
    property CONFIGURACIONPATHJPG1: string read FCONFIGURACIONPATHJPG1 write FCONFIGURACIONPATHJPG1;
    property CONFIGURACIONPATHMM1: string read FCONFIGURACIONPATHMM1 write FCONFIGURACIONPATHMM1;
    property CONFIGURACIONPATHSW1: string read FCONFIGURACIONPATHSW1 write FCONFIGURACIONPATHSW1;
    property CONFIGURACIONPATHXMLFondos1: string read FCONFIGURACIONPATHXMLFondos1 write FCONFIGURACIONPATHXMLFondos1;
    property CONFIGURACIONPATHJPGFondos1: string read FCONFIGURACIONPATHJPGFondos1 write FCONFIGURACIONPATHJPGFondos1;
    property CONFIGURACIONSYNCMULTIPLAYER: Integer read FCONFIGURACIONSYNCMULTIPLAYER write FCONFIGURACIONSYNCMULTIPLAYER;
    property CONFIGURACIONSYNCMULTIPLAYERMASTER: Integer read FCONFIGURACIONSYNCMULTIPLAYERMASTER write FCONFIGURACIONSYNCMULTIPLAYERMASTER;
    property CONFIGURACIONVIDEORENDERER: Integer read FCONFIGURACIONVIDEORENDERER write FCONFIGURACIONVIDEORENDERER;
    property CONFIGURACIONWEBRENDERER: Integer read FCONFIGURACIONWEBRENDERER write FCONFIGURACIONWEBRENDERER;
    property CONFIGURACIONMOD_REPRO_MKD: Integer read FCONFIGURACIONMOD_REPRO_MKD write FCONFIGURACIONMOD_REPRO_MKD;
    property CONFIGURACIONURLCACHEDYNA: string read FCONFIGURACIONURLCACHEDYNA write FCONFIGURACIONURLCACHEDYNA;
    property CONFIGURACIONID_MASTER_CACHE: Integer read FCONFIGURACIONID_MASTER_CACHE write FCONFIGURACIONID_MASTER_CACHE;
    property CONFIGURACIONBDAUDIENCIA: string read FCONFIGURACIONBDAUDIENCIA write FCONFIGURACIONBDAUDIENCIA;
    property CONFIGURACIONLOCAL5555: string read FCONFIGURACIONLOCAL5555 write FCONFIGURACIONLOCAL5555;
    property CONFIGURACIONVERSION: string read FCONFIGURACIONVERSION write FCONFIGURACIONVERSION;
    property CONFIGURACIONIDSISTEMA: Integer read FCONFIGURACIONIDSISTEMA write FCONFIGURACIONIDSISTEMA;
    property CONFIGURACIONBACKOFFICE: Integer read FCONFIGURACIONBACKOFFICE write FCONFIGURACIONBACKOFFICE;
    property CONFIGURACIONFFPLAYERFIT: string read FCONFIGURACIONFFPLAYERFIT write FCONFIGURACIONFFPLAYERFIT;
    property CONFIGURACIONCOM_PORT: Integer read FCONFIGURACIONCOM_PORT write FCONFIGURACIONCOM_PORT;
    property CONFIGURACIONFFLOGGER: Integer read FCONFIGURACIONFFLOGGER write FCONFIGURACIONFFLOGGER;
    property CONFIGURACIONDEBUGTTY: Integer read FCONFIGURACIONDEBUGTTY write FCONFIGURACIONDEBUGTTY;
    property CONFIGURACIONCHRNOPOPMENU: string read FCONFIGURACIONCHRNOPOPMENU write FCONFIGURACIONCHRNOPOPMENU;
    property CONFIGURACIONUDP_MCAST_LISTENER: string read FCONFIGURACIONUDP_MCAST_LISTENER write FCONFIGURACIONUDP_MCAST_LISTENER;
    property CONFIGURACIONMCASTPORT: Integer read FCONFIGURACIONMCASTPORT write FCONFIGURACIONMCASTPORT;
    property CONFIGURACIONCONTROLNTP: string read FCONFIGURACIONCONTROLNTP write FCONFIGURACIONCONTROLNTP;
    property CONFIGURACIONWEBEXTERNACHR: string read FCONFIGURACIONWEBEXTERNACHR write FCONFIGURACIONWEBEXTERNACHR;
    property CONFIGURACIONFICPASTILLAVIDEO: string read FCONFIGURACIONFICPASTILLAVIDEO write FCONFIGURACIONFICPASTILLAVIDEO;
    property CONFIGURACIONPASTILLAVIDEO: string read FCONFIGURACIONPASTILLAVIDEO write FCONFIGURACIONPASTILLAVIDEO;
    property CONFIGURACIONREFRESHWEB: string read FCONFIGURACIONREFRESHWEB write FCONFIGURACIONREFRESHWEB;
    property CONFIGURACIONAPIWEB: string read FCONFIGURACIONAPIWEB write FCONFIGURACIONAPIWEB;
    property CONFIGURACIONAPIUSER: string read FCONFIGURACIONAPIUSER write FCONFIGURACIONAPIUSER;
    property CONFIGURACIONAPIPASS: string read FCONFIGURACIONAPIPASS write FCONFIGURACIONAPIPASS;
    property CONFIGURACIONAPIPORT: Integer read FCONFIGURACIONAPIPORT write FCONFIGURACIONAPIPORT;
    property CONFIGURACIONSEG_BLOQUEO_ALIVE: Integer read FCONFIGURACIONSEG_BLOQUEO_ALIVE write FCONFIGURACIONSEG_BLOQUEO_ALIVE;
    property CONFIGURACIONSYNCMCASTGROUP: string read FCONFIGURACIONSYNCMCASTGROUP write FCONFIGURACIONSYNCMCASTGROUP;
    property CONFIGURACIONSYNCMCASTPORT: Integer read FCONFIGURACIONSYNCMCASTPORT write FCONFIGURACIONSYNCMCASTPORT;
    property CONFIGURACIONCICLOCUNRELLENO: Integer read FCONFIGURACIONCICLOCUNRELLENO write FCONFIGURACIONCICLOCUNRELLENO;
    property CONFIGURACIONURLUDPORD: string read FCONFIGURACIONURLUDPORD write FCONFIGURACIONURLUDPORD;
    property CONFIGURACIONAUDIENCIAINTERACTIVA: string read FCONFIGURACIONAUDIENCIAINTERACTIVA write FCONFIGURACIONAUDIENCIAINTERACTIVA;
    property CONFIGURACIONPULLORDENES: string read FCONFIGURACIONPULLORDENES write FCONFIGURACIONPULLORDENES;

    {Section: CENTINELA}
    property CENTINELAHBEAT: string read FCENTINELAHBEAT write FCENTINELAHBEAT;
    property CENTINELADIALOGOS: string read FCENTINELADIALOGOS write FCENTINELADIALOGOS;
    property CENTINELATIMEOUT_BLOQUEO: Integer read FCENTINELATIMEOUT_BLOQUEO write FCENTINELATIMEOUT_BLOQUEO;
    property CENTINELATIMEOUT_CPUALTA: Integer read FCENTINELATIMEOUT_CPUALTA write FCENTINELATIMEOUT_CPUALTA;
    property CENTINELACONFW: string read FCENTINELACONFW write FCENTINELACONFW;
    property CENTINELAMAXIMO_CPU: Integer read FCENTINELAMAXIMO_CPU write FCENTINELAMAXIMO_CPU;
    property CENTINELAMAXIMO_MEMORIA: Integer read FCENTINELAMAXIMO_MEMORIA write FCENTINELAMAXIMO_MEMORIA;
    property CENTINELACLASENOTIF_CENTINELA: string read FCENTINELACLASENOTIF_CENTINELA write FCENTINELACLASENOTIF_CENTINELA;
    property CENTINELACLASE_COMANDOS: string read FCENTINELACLASE_COMANDOS write FCENTINELACLASE_COMANDOS;
    property CENTINELAVERSION: string read FCENTINELAVERSION write FCENTINELAVERSION;
    property CENTINELAPROGRAMAS_NO_CERRAR: string read FCENTINELAPROGRAMAS_NO_CERRAR write FCENTINELAPROGRAMAS_NO_CERRAR;
    property CENTINELAHBEATUDP_TIME: Integer read FCENTINELAHBEATUDP_TIME write FCENTINELAHBEATUDP_TIME;

    {Section: SOS}
    property SOSINI_EMERGENCIA: string read FSOSINI_EMERGENCIA write FSOSINI_EMERGENCIA;

    {Section: CRONOS}
    property CRONOSTMRCRONOS: Integer read FCRONOSTMRCRONOS write FCRONOSTMRCRONOS;
    property CRONOSCENTEMITE: Integer read FCRONOSCENTEMITE write FCRONOSCENTEMITE;
    property CRONOSREPESCACUNIA: Integer read FCRONOSREPESCACUNIA write FCRONOSREPESCACUNIA;
    property CRONOSBOFFSET: Integer read FCRONOSBOFFSET write FCRONOSBOFFSET;

    {Section: PlayerWEB}
    property PlayerWEBurl_startup: string read FPlayerWEBurl_startup write FPlayerWEBurl_startup;
    property PlayerWEBurl_base_ws: string read FPlayerWEBurl_base_ws write FPlayerWEBurl_base_ws;
    property PlayerWEBancho: Integer read FPlayerWEBancho write FPlayerWEBancho;
    property PlayerWEBalto: Integer read FPlayerWEBalto write FPlayerWEBalto;
    property PlayerWEBx: Integer read FPlayerWEBx write FPlayerWEBx;
    property PlayerWEBy: Integer read FPlayerWEBy write FPlayerWEBy;
    property PlayerWEBintervalo_refresh: Integer read FPlayerWEBintervalo_refresh write FPlayerWEBintervalo_refresh;
    property PlayerWEBintervalo_check: Integer read FPlayerWEBintervalo_check write FPlayerWEBintervalo_check;
    property PlayerWEBfuncion_check: string read FPlayerWEBfuncion_check write FPlayerWEBfuncion_check;
    property PlayerWEBintervalo_info: Integer read FPlayerWEBintervalo_info write FPlayerWEBintervalo_info;
  end;

var
  IniOptions: TIniOptions = nil;

implementation

procedure TIniOptions.LoadSettings(Ini: TIniFile);
begin
  if Ini <> nil then
  begin
    {Section: CONFIGURACION}
    FCONFIGURACIONUDPLISTENER := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUDPLISTENER, '192.168.84.20');
    FCONFIGURACIONID := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONID, 016878);
    FCONFIGURACIONCREALOGTTY := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCREALOGTTY, 'S');
    FCONFIGURACIONCONEXIONNORMAL := Ini.ReadDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONEXIONNORMAL, StrToDateTime('01:05:40'));
    FCONFIGURACIONANCHOVENTANACONEXION := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONANCHOVENTANACONEXION, 7);
    FCONFIGURACIONPERIODO := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPERIODO, 1);
    FCONFIGURACIONCBUSCARORDENES := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCBUSCARORDENES, 0);
    FCONFIGURACIONSEPARARCANALES := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONSEPARARCANALES, 'N');
    FCONFIGURACIONMAXTIEMPODESCARGA := Ini.ReadDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONMAXTIEMPODESCARGA, StrToDateTime('00:59'));
    FCONFIGURACIONMINCONEXION := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMINCONEXION, 5);
    FCONFIGURACIONMIN_CONEXION := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMIN_CONEXION, 0);
    FCONFIGURACIONPROPORCION := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPROPORCION, 25);
    FCONFIGURACIONULTIMOCANAL := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONULTIMOCANAL, 705);
    FCONFIGURACIONTCACHE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONTCACHE, 24996);
    FCONFIGURACIONNIVELLOG := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONNIVELLOG, 1);
    FCONFIGURACIONVAL_INTERVALOALIVE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONVAL_INTERVALOALIVE, 15);
    FCONFIGURACIONUSR_FTP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUSR_FTP, 'sthilodes');
    FCONFIGURACIONPWD_FTP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPWD_FTP, 'sthd');
    FCONFIGURACIONCLASECONEX := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCLASECONEX, 1);
    FCONFIGURACIONFTPPASIVO := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFTPPASIVO, 'S');
    FCONFIGURACIONMODOFTP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONMODOFTP, 'P');
    FCONFIGURACIONURLUDP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONURLUDP, 'http://127.0.0.1/ws/comandos.cfm');
    FCONFIGURACIONTURLUDP := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONTURLUDP, 1);
    FCONFIGURACIONFTP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFTP, '');
    FCONFIGURACIONPROXY := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPROXY, '');
    FCONFIGURACIONPROXYPORT := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPROXYPORT, '');
    FCONFIGURACIONBWLimit := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONBWLimit, -1);
    FCONFIGURACIONCLASENOTIF := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCLASENOTIF, 'UDP');
    FCONFIGURACIONINTERVALOALIVE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONINTERVALOALIVE, 15);
    FCONFIGURACIONVIDEO := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONVIDEO, 'S');
    FCONFIGURACIONPANTALLAS := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLAS, 1);
    FCONFIGURACIONMODELOPANTALLA1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONMODELOPANTALLA1, '');
    FCONFIGURACIONPANTALLA1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA1, '0,0');
    FCONFIGURACIONPANTALLA2 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA2, '1024,1');
    FCONFIGURACIONPANTALLA3 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA3, '1024,0');
    FCONFIGURACIONPANTALLA4 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA4, '1024,0');
    FCONFIGURACIONPANTALLA5 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA5, '1024,0');
    FCONFIGURACIONRATONX := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONX, 0);
    FCONFIGURACIONRATONY := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONY, 0);
    FCONFIGURACIONRATONW := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONW, 1920);
    FCONFIGURACIONRATONH := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONH, 1080);
    FCONFIGURACIONFON_BCO_FLASH := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFON_BCO_FLASH, 'S');
    FCONFIGURACIONFON_BCO_VIDEO := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFON_BCO_VIDEO, 'S');
    FCONFIGURACIONFON_BCO_IMAGEN := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFON_BCO_IMAGEN, 'S');
    FCONFIGURACIONCONSOLATOP := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONSOLATOP, 80);
    FCONFIGURACIONCONSOLALEFT := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONSOLALEFT, 1300);
    FCONFIGURACIONONOFF := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONONOFF, 'N');
    FCONFIGURACIONENCENDIDO := Ini.ReadDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONENCENDIDO, StrToDateTime('00:00:01'));
    FCONFIGURACIONAPAGADO := Ini.ReadDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPAGADO, StrToDateTime('23:59:59'));
    FCONFIGURACIONCOD_CLIENTE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOD_CLIENTE, 1);
    FCONFIGURACIONNOM_UBICACION := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONNOM_UBICACION, '');
    FCONFIGURACIONUSERID := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUSERID, '');
    FCONFIGURACIONCOD_GRUPO := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOD_GRUPO, 4198);
    FCONFIGURACIONNOM_ZONA := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONNOM_ZONA, '');
    FCONFIGURACIONZONAHORARIA := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONZONAHORARIA, 0);
    FCONFIGURACIONCPO_LOCAL := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCPO_LOCAL, 07006);
    FCONFIGURACIONLANG := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONLANG, 'SPANISH');
    FCONFIGURACIONCOD_SERVICIO := Ini.ReadFloat(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOD_SERVICIO, 791005062001);
    FCONFIGURACIONFTP1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFTP1, '192.168.84.20');
    FCONFIGURACIONPORT1 := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPORT1, 21);
    FCONFIGURACIONPATH1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATH1, '\HMSIP2\mp3\');
    FCONFIGURACIONPATHCUNIAS1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHCUNIAS1, '\HMSIP2\cunias\');
    FCONFIGURACIONPATHORD1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHORD1, '\HMSIP2\ord\');
    FCONFIGURACIONPATHPLAYLIST1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHPLAYLIST1, '\HMSIP2\cor\');
    FCONFIGURACIONPATHPLAYLISTCUNIA1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHPLAYLISTCUNIA1, '\HMSIP2\cun\');
    FCONFIGURACIONPATHPLAYLISTCUNIAS1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHPLAYLISTCUNIAS1, '\HMSIP2\cun\');
    FCONFIGURACIONPATHINI1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHINI1, '\HMSIP2\ini\');
    FCONFIGURACIONPATHJPG1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHJPG1, '\HMSIP2\jpgfondos\');
    FCONFIGURACIONPATHMM1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHMM1, '\HMSIP2\mm\');
    FCONFIGURACIONPATHSW1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHSW1, '\HMSIP2\sw\');
    FCONFIGURACIONPATHXMLFondos1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHXMLFondos1, '\HMSIP2\XMLfondos\');
    FCONFIGURACIONPATHJPGFondos1 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHJPGFondos1, '\hmsip2\JPGFondos');
    FCONFIGURACIONSYNCMULTIPLAYER := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMULTIPLAYER, 0);
    FCONFIGURACIONSYNCMULTIPLAYERMASTER := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMULTIPLAYERMASTER, 0);
    FCONFIGURACIONVIDEORENDERER := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONVIDEORENDERER, 1);
    FCONFIGURACIONWEBRENDERER := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONWEBRENDERER, 0);
    FCONFIGURACIONMOD_REPRO_MKD := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMOD_REPRO_MKD, 4);
    FCONFIGURACIONURLCACHEDYNA := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONURLCACHEDYNA, '192.168.1.170/mm/');
    FCONFIGURACIONID_MASTER_CACHE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONID_MASTER_CACHE, 100364);
    FCONFIGURACIONBDAUDIENCIA := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONBDAUDIENCIA, 'C:\Users\nemesis\AppData\Roaming\Wututu\PersonCounterSoftware\local.db');
    FCONFIGURACIONLOCAL5555 := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONLOCAL5555, 'N');
    FCONFIGURACIONVERSION := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONVERSION, 'V.22.02.u');
    FCONFIGURACIONIDSISTEMA := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONIDSISTEMA, 000001);
    FCONFIGURACIONBACKOFFICE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONBACKOFFICE, 000001);
    FCONFIGURACIONFFPLAYERFIT := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFFPLAYERFIT, 'N');
    FCONFIGURACIONCOM_PORT := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOM_PORT, -1);
    FCONFIGURACIONFFLOGGER := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONFFLOGGER, 0);
    FCONFIGURACIONDEBUGTTY := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONDEBUGTTY, 0);
    FCONFIGURACIONCHRNOPOPMENU := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCHRNOPOPMENU, 'S');
    FCONFIGURACIONUDP_MCAST_LISTENER := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUDP_MCAST_LISTENER, '10.32.0.5');
    FCONFIGURACIONMCASTPORT := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMCASTPORT, 5000);
    FCONFIGURACIONCONTROLNTP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONTROLNTP, 'N');
    FCONFIGURACIONWEBEXTERNACHR := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONWEBEXTERNACHR, 'N');
    FCONFIGURACIONFICPASTILLAVIDEO := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFICPASTILLAVIDEO, 'pastillaVideoclip.swf');
    FCONFIGURACIONPASTILLAVIDEO := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPASTILLAVIDEO, 'N');
    FCONFIGURACIONREFRESHWEB := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONREFRESHWEB, 'N');
    FCONFIGURACIONAPIWEB := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIWEB, 'S');
    FCONFIGURACIONAPIUSER := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIUSER, '');
    FCONFIGURACIONAPIPASS := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIPASS, '');
    FCONFIGURACIONAPIPORT := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIPORT, 55555);
    FCONFIGURACIONSEG_BLOQUEO_ALIVE := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSEG_BLOQUEO_ALIVE, 10);
    FCONFIGURACIONSYNCMCASTGROUP := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMCASTGROUP, '239.11.0.5');
    FCONFIGURACIONSYNCMCASTPORT := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMCASTPORT, 5005);
    FCONFIGURACIONCICLOCUNRELLENO := Ini.ReadInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCICLOCUNRELLENO, 5);
    FCONFIGURACIONURLUDPORD := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONURLUDPORD, 'http://ordenes.cfm');
    FCONFIGURACIONAUDIENCIAINTERACTIVA := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAUDIENCIAINTERACTIVA, 'N');
    FCONFIGURACIONPULLORDENES := Ini.ReadString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPULLORDENES, 'N');

    {Section: CENTINELA}
    FCENTINELAHBEAT := Ini.ReadString(csIniCENTINELASection, csIniCENTINELAHBEAT, 'N');
    FCENTINELADIALOGOS := Ini.ReadString(csIniCENTINELASection, csIniCENTINELADIALOGOS, 'S');
    FCENTINELATIMEOUT_BLOQUEO := Ini.ReadInteger(csIniCENTINELASection, csIniCENTINELATIMEOUT_BLOQUEO, 4);
    FCENTINELATIMEOUT_CPUALTA := Ini.ReadInteger(csIniCENTINELASection, csIniCENTINELATIMEOUT_CPUALTA, 4);
    FCENTINELACONFW := Ini.ReadString(csIniCENTINELASection, csIniCENTINELACONFW, 'S');
    FCENTINELAMAXIMO_CPU := Ini.ReadInteger(csIniCENTINELASection, csIniCENTINELAMAXIMO_CPU, 90);
    FCENTINELAMAXIMO_MEMORIA := Ini.ReadInteger(csIniCENTINELASection, csIniCENTINELAMAXIMO_MEMORIA, 90);
    FCENTINELACLASENOTIF_CENTINELA := Ini.ReadString(csIniCENTINELASection, csIniCENTINELACLASENOTIF_CENTINELA, 'UDP');
    FCENTINELACLASE_COMANDOS := Ini.ReadString(csIniCENTINELASection, csIniCENTINELACLASE_COMANDOS, 'C');
    FCENTINELAVERSION := Ini.ReadString(csIniCENTINELASection, csIniCENTINELAVERSION, 'V6.43');
    FCENTINELAPROGRAMAS_NO_CERRAR := Ini.ReadString(csIniCENTINELASection, csIniCENTINELAPROGRAMAS_NO_CERRAR, 'TUNEUP,TEAMVIEWER,MCAFEE,DEL AN·LISIS EN TIEMPO REAL');
    FCENTINELAHBEATUDP_TIME := Ini.ReadInteger(csIniCENTINELASection, csIniCENTINELAHBEATUDP_TIME, 0);

    {Section: SOS}
    FSOSINI_EMERGENCIA := Ini.ReadString(csIniSOSSection, csIniSOSINI_EMERGENCIA, 'N');

    {Section: CRONOS}
    FCRONOSTMRCRONOS := Ini.ReadInteger(csIniCRONOSSection, csIniCRONOSTMRCRONOS, 100);
    FCRONOSCENTEMITE := Ini.ReadInteger(csIniCRONOSSection, csIniCRONOSCENTEMITE, 200);
    FCRONOSREPESCACUNIA := Ini.ReadInteger(csIniCRONOSSection, csIniCRONOSREPESCACUNIA, 0);
    FCRONOSBOFFSET := Ini.ReadInteger(csIniCRONOSSection, csIniCRONOSBOFFSET, 10);

    {Section: PlayerWEB}
    FPlayerWEBurl_startup := Ini.ReadString(csIniPlayerWEBSection, csIniPlayerWEBurl_startup, 'http://enaire.test/panel/get/2');
    FPlayerWEBurl_base_ws := Ini.ReadString(csIniPlayerWEBSection, csIniPlayerWEBurl_base_ws, 'http://enaire.test/api/');
    FPlayerWEBancho := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBancho, 1920);
    FPlayerWEBalto := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBalto, 1080);
    FPlayerWEBx := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBx, 0);
    FPlayerWEBy := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBy, 0);
    FPlayerWEBintervalo_refresh := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBintervalo_refresh, 90);
    FPlayerWEBintervalo_check := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBintervalo_check, 60);
    FPlayerWEBfuncion_check := Ini.ReadString(csIniPlayerWEBSection, csIniPlayerWEBfuncion_check, 'checkpanel/2');
    FPlayerWEBintervalo_info := Ini.ReadInteger(csIniPlayerWEBSection, csIniPlayerWEBintervalo_info, 900);
  end;
end;

procedure TIniOptions.SaveSettings(Ini: TIniFile);
begin
  if Ini <> nil then
  begin
    {Section: CONFIGURACION}
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUDPLISTENER, FCONFIGURACIONUDPLISTENER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONID, FCONFIGURACIONID);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCREALOGTTY, FCONFIGURACIONCREALOGTTY);
    Ini.WriteDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONEXIONNORMAL, FCONFIGURACIONCONEXIONNORMAL);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONANCHOVENTANACONEXION, FCONFIGURACIONANCHOVENTANACONEXION);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPERIODO, FCONFIGURACIONPERIODO);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCBUSCARORDENES, FCONFIGURACIONCBUSCARORDENES);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONSEPARARCANALES, FCONFIGURACIONSEPARARCANALES);
    Ini.WriteDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONMAXTIEMPODESCARGA, FCONFIGURACIONMAXTIEMPODESCARGA);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMINCONEXION, FCONFIGURACIONMINCONEXION);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMIN_CONEXION, FCONFIGURACIONMIN_CONEXION);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPROPORCION, FCONFIGURACIONPROPORCION);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONULTIMOCANAL, FCONFIGURACIONULTIMOCANAL);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONTCACHE, FCONFIGURACIONTCACHE);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONNIVELLOG, FCONFIGURACIONNIVELLOG);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONVAL_INTERVALOALIVE, FCONFIGURACIONVAL_INTERVALOALIVE);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUSR_FTP, FCONFIGURACIONUSR_FTP);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPWD_FTP, FCONFIGURACIONPWD_FTP);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCLASECONEX, FCONFIGURACIONCLASECONEX);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFTPPASIVO, FCONFIGURACIONFTPPASIVO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONMODOFTP, FCONFIGURACIONMODOFTP);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONURLUDP, FCONFIGURACIONURLUDP);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONTURLUDP, FCONFIGURACIONTURLUDP);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFTP, FCONFIGURACIONFTP);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPROXY, FCONFIGURACIONPROXY);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPROXYPORT, FCONFIGURACIONPROXYPORT);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONBWLimit, FCONFIGURACIONBWLimit);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCLASENOTIF, FCONFIGURACIONCLASENOTIF);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONINTERVALOALIVE, FCONFIGURACIONINTERVALOALIVE);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONVIDEO, FCONFIGURACIONVIDEO);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLAS, FCONFIGURACIONPANTALLAS);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONMODELOPANTALLA1, FCONFIGURACIONMODELOPANTALLA1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA1, FCONFIGURACIONPANTALLA1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA2, FCONFIGURACIONPANTALLA2);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA3, FCONFIGURACIONPANTALLA3);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA4, FCONFIGURACIONPANTALLA4);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPANTALLA5, FCONFIGURACIONPANTALLA5);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONX, FCONFIGURACIONRATONX);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONY, FCONFIGURACIONRATONY);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONW, FCONFIGURACIONRATONW);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONRATONH, FCONFIGURACIONRATONH);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFON_BCO_FLASH, FCONFIGURACIONFON_BCO_FLASH);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFON_BCO_VIDEO, FCONFIGURACIONFON_BCO_VIDEO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFON_BCO_IMAGEN, FCONFIGURACIONFON_BCO_IMAGEN);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONSOLATOP, FCONFIGURACIONCONSOLATOP);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONSOLALEFT, FCONFIGURACIONCONSOLALEFT);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONONOFF, FCONFIGURACIONONOFF);
    Ini.WriteDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONENCENDIDO, FCONFIGURACIONENCENDIDO);
    Ini.WriteDateTime(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPAGADO, FCONFIGURACIONAPAGADO);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOD_CLIENTE, FCONFIGURACIONCOD_CLIENTE);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONNOM_UBICACION, FCONFIGURACIONNOM_UBICACION);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUSERID, FCONFIGURACIONUSERID);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOD_GRUPO, FCONFIGURACIONCOD_GRUPO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONNOM_ZONA, FCONFIGURACIONNOM_ZONA);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONZONAHORARIA, FCONFIGURACIONZONAHORARIA);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCPO_LOCAL, FCONFIGURACIONCPO_LOCAL);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONLANG, FCONFIGURACIONLANG);
    Ini.WriteFloat(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOD_SERVICIO, FCONFIGURACIONCOD_SERVICIO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFTP1, FCONFIGURACIONFTP1);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONPORT1, FCONFIGURACIONPORT1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATH1, FCONFIGURACIONPATH1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHCUNIAS1, FCONFIGURACIONPATHCUNIAS1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHORD1, FCONFIGURACIONPATHORD1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHPLAYLIST1, FCONFIGURACIONPATHPLAYLIST1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHPLAYLISTCUNIA1, FCONFIGURACIONPATHPLAYLISTCUNIA1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHPLAYLISTCUNIAS1, FCONFIGURACIONPATHPLAYLISTCUNIAS1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHINI1, FCONFIGURACIONPATHINI1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHJPG1, FCONFIGURACIONPATHJPG1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHMM1, FCONFIGURACIONPATHMM1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHSW1, FCONFIGURACIONPATHSW1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHXMLFondos1, FCONFIGURACIONPATHXMLFondos1);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPATHJPGFondos1, FCONFIGURACIONPATHJPGFondos1);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMULTIPLAYER, FCONFIGURACIONSYNCMULTIPLAYER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMULTIPLAYERMASTER, FCONFIGURACIONSYNCMULTIPLAYERMASTER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONVIDEORENDERER, FCONFIGURACIONVIDEORENDERER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONWEBRENDERER, FCONFIGURACIONWEBRENDERER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMOD_REPRO_MKD, FCONFIGURACIONMOD_REPRO_MKD);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONURLCACHEDYNA, FCONFIGURACIONURLCACHEDYNA);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONID_MASTER_CACHE, FCONFIGURACIONID_MASTER_CACHE);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONBDAUDIENCIA, FCONFIGURACIONBDAUDIENCIA);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONLOCAL5555, FCONFIGURACIONLOCAL5555);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONVERSION, FCONFIGURACIONVERSION);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONIDSISTEMA, FCONFIGURACIONIDSISTEMA);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONBACKOFFICE, FCONFIGURACIONBACKOFFICE);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFFPLAYERFIT, FCONFIGURACIONFFPLAYERFIT);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCOM_PORT, FCONFIGURACIONCOM_PORT);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONFFLOGGER, FCONFIGURACIONFFLOGGER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONDEBUGTTY, FCONFIGURACIONDEBUGTTY);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCHRNOPOPMENU, FCONFIGURACIONCHRNOPOPMENU);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONUDP_MCAST_LISTENER, FCONFIGURACIONUDP_MCAST_LISTENER);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONMCASTPORT, FCONFIGURACIONMCASTPORT);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONCONTROLNTP, FCONFIGURACIONCONTROLNTP);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONWEBEXTERNACHR, FCONFIGURACIONWEBEXTERNACHR);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONFICPASTILLAVIDEO, FCONFIGURACIONFICPASTILLAVIDEO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPASTILLAVIDEO, FCONFIGURACIONPASTILLAVIDEO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONREFRESHWEB, FCONFIGURACIONREFRESHWEB);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIWEB, FCONFIGURACIONAPIWEB);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIUSER, FCONFIGURACIONAPIUSER);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIPASS, FCONFIGURACIONAPIPASS);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONAPIPORT, FCONFIGURACIONAPIPORT);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSEG_BLOQUEO_ALIVE, FCONFIGURACIONSEG_BLOQUEO_ALIVE);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMCASTGROUP, FCONFIGURACIONSYNCMCASTGROUP);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONSYNCMCASTPORT, FCONFIGURACIONSYNCMCASTPORT);
    Ini.WriteInteger(csIniCONFIGURACIONSection, csIniCONFIGURACIONCICLOCUNRELLENO, FCONFIGURACIONCICLOCUNRELLENO);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONURLUDPORD, FCONFIGURACIONURLUDPORD);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONAUDIENCIAINTERACTIVA, FCONFIGURACIONAUDIENCIAINTERACTIVA);
    Ini.WriteString(csIniCONFIGURACIONSection, csIniCONFIGURACIONPULLORDENES, FCONFIGURACIONPULLORDENES);

    {Section: CENTINELA}
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELAHBEAT, FCENTINELAHBEAT);
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELADIALOGOS, FCENTINELADIALOGOS);
    Ini.WriteInteger(csIniCENTINELASection, csIniCENTINELATIMEOUT_BLOQUEO, FCENTINELATIMEOUT_BLOQUEO);
    Ini.WriteInteger(csIniCENTINELASection, csIniCENTINELATIMEOUT_CPUALTA, FCENTINELATIMEOUT_CPUALTA);
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELACONFW, FCENTINELACONFW);
    Ini.WriteInteger(csIniCENTINELASection, csIniCENTINELAMAXIMO_CPU, FCENTINELAMAXIMO_CPU);
    Ini.WriteInteger(csIniCENTINELASection, csIniCENTINELAMAXIMO_MEMORIA, FCENTINELAMAXIMO_MEMORIA);
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELACLASENOTIF_CENTINELA, FCENTINELACLASENOTIF_CENTINELA);
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELACLASE_COMANDOS, FCENTINELACLASE_COMANDOS);
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELAVERSION, FCENTINELAVERSION);
    Ini.WriteString(csIniCENTINELASection, csIniCENTINELAPROGRAMAS_NO_CERRAR, FCENTINELAPROGRAMAS_NO_CERRAR);
    Ini.WriteInteger(csIniCENTINELASection, csIniCENTINELAHBEATUDP_TIME, FCENTINELAHBEATUDP_TIME);

    {Section: SOS}
    Ini.WriteString(csIniSOSSection, csIniSOSINI_EMERGENCIA, FSOSINI_EMERGENCIA);

    {Section: CRONOS}
    Ini.WriteInteger(csIniCRONOSSection, csIniCRONOSTMRCRONOS, FCRONOSTMRCRONOS);
    Ini.WriteInteger(csIniCRONOSSection, csIniCRONOSCENTEMITE, FCRONOSCENTEMITE);
    Ini.WriteInteger(csIniCRONOSSection, csIniCRONOSREPESCACUNIA, FCRONOSREPESCACUNIA);
    Ini.WriteInteger(csIniCRONOSSection, csIniCRONOSBOFFSET, FCRONOSBOFFSET);

    {Section: PlayerWEB}
    Ini.WriteString(csIniPlayerWEBSection, csIniPlayerWEBurl_startup, FPlayerWEBurl_startup);
    Ini.WriteString(csIniPlayerWEBSection, csIniPlayerWEBurl_base_ws, FPlayerWEBurl_base_ws);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBancho, FPlayerWEBancho);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBalto, FPlayerWEBalto);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBx, FPlayerWEBx);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBy, FPlayerWEBy);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBintervalo_refresh, FPlayerWEBintervalo_refresh);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBintervalo_check, FPlayerWEBintervalo_check);
    Ini.WriteString(csIniPlayerWEBSection, csIniPlayerWEBfuncion_check, FPlayerWEBfuncion_check);
    Ini.WriteInteger(csIniPlayerWEBSection, csIniPlayerWEBintervalo_info, FPlayerWEBintervalo_info);
  end;
end;

procedure TIniOptions.LoadFromFile(const FileName: string);
var
  Ini: TIniFile;
begin
  Ini := TIniFile.Create(FileName);
  try
    LoadSettings(Ini);
  finally
    Ini.Free;
  end;
end;

procedure TIniOptions.SaveToFile(const FileName: string);
var
  Ini: TIniFile;
begin
  Ini := TIniFile.Create(FileName);
  try
    SaveSettings(Ini);
  finally
    Ini.Free;
  end;
end;

initialization
  IniOptions := TIniOptions.Create;

finalization
  IniOptions.Free;

end.

